#!/bin/bash

cp -a $REPO ./build/

${PIP} install -r $REPO/requirements.txt
mkdir -p build/oneplus/oneplusmvp/static/
${PIP} freeze > build/oneplus/oneplusmvp/static/pip-freeze.txt
git --git-dir $REPO/.git log -50 --pretty=format:'%ai - %h %s (%cr) <%an>' > build/oneplus/oneplusmvp/static/git-commits.txt
